# SPDX-License-Identifier: Apache-2.0
#
# luci-app-phantun - LuCI interface for Phantun (UDP over FakeTCP obfuscator)
#
# The Phantun binaries themselves are NOT bundled. On first use the web UI
# offers an "initialize" action that downloads the correct prebuilt binary
# for the running architecture from GitHub (via configurable acceleration
# mirrors), so this package stays tiny and works on any kernel/arch.

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-phantun
PKG_VERSION:=1.2.2
PKG_RELEASE:=1

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Dage

LUCI_TITLE:=LuCI support for Phantun (UDP over FakeTCP)
# curl: header-race mirror probing + downloads. unzip: extract release zip.
# kmod-tun: Phantun creates TUN interfaces.
LUCI_DEPENDS:=+kmod-tun +unzip +curl
LUCI_PKGARCH:=all

# bind-host | drill: either DNS lookup tool satisfies the DDNS monitor's
# domain resolution. EXTRA_DEPENDS writes the OR relation straight into the
# ipk Depends field without generating a Kconfig select (which cannot express
# OR and would break the build), exactly like luci-app-udp2raw-ultra.
LUCI_EXTRA_DEPENDS:=bind-host | drill
EXTRA_DEPENDS:=bind-host | drill

# NOTE: postrm must be defined BEFORE including luci.mk, because luci.mk calls
# BuildPackage at include time; definitions placed after the include are
# ignored. prerm is auto-generated by the build system (it stops/disables the
# init.d service), so we do all cleanup in postrm instead: the runtime-
# downloaded binaries are NOT tracked by opkg and must be removed by hand.
define Package/luci-app-phantun/postrm
#!/bin/sh
[ -n "$${IPKG_INSTROOT}" ] && exit 0
# Keep everything on upgrade; only clean up on a real uninstall.
[ "$$PKG_UPGRADE" = "1" ] && exit 0
# Make sure no phantun processes survive (init.d prerm stops the procd
# instances, but kill any stragglers just in case), then remove the
# runtime-downloaded binaries and all leftover config/state/logs.
killall phantun_server phantun_client 2>/dev/null
# Remove any server-exception ip rules / dedicated route table we installed
# (route_via_wan), so no stale policy routing survives the uninstall.
[ -x /usr/share/phantun/route.sh ] && /usr/share/phantun/route.sh flush_all 2>/dev/null
rm -f /usr/bin/phantun_server /usr/bin/phantun_client
rm -f /tmp/phantun_init.status /tmp/phantun_init.log
rm -rf /tmp/phantun_dl /var/run/phantun
rm -f /etc/config/phantun
rm -rf /usr/share/phantun
rm -f /var/log/phantun*
exit 0
endef

# Enable the service on install so rules start automatically at boot. Only
# enabled rules (enabled='1') are actually started by start_service, so this
# is safe even before the user configures anything. Also reloads rpcd/uhttpd
# so the LuCI ACL/menu take effect immediately.
define Package/luci-app-phantun/postinst
#!/bin/sh
[ -n "$${IPKG_INSTROOT}" ] && exit 0
/etc/init.d/phantun enable 2>/dev/null
exit 0
endef

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
